### ISSUE TITLE
Failure when server_flags are not passed

### ISSUE THREAD

**Issue by rancher-max** [rancher/distros-test-framework#86]
There is some failure to retrieve node statuses when the server_flags are passed as an empty string. It panics in a timeout.

**Comment by fmoral2** [comment]
please @aganesh-suse  add the full logs + all config you are passing in + the test ran + any additional useful info

**Comment by aganesh-suse** [comment]
Error Log:
```
PASSED! Test: Start Up with no issues
•panic: test timed out after 45m0s
running tests:
	TestSecretsEncryptionSuite (45m0s)

goroutine 447 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2366 +0x30c
created by time.goFunc
	/usr/local/go/src/time/sleep.go:177 +0x38

goroutine 1 [chan receive, 45 minutes]:
testing.(*T).Run(0x40004b6000, {0xcbd018?, 0x40005ffab8?}, 0xd283c8)
	/usr/local/go/src/testing/testing.go:1750 +0x32c
testing.runTests.func1(0x40004b6000)
	/usr/local/go/src/testing/testing.go:2161 +0x40
testing.tRunner(0x40004b6000, 0x40005ffbd8)
	/usr/local/go/src/testing/testing.go:1689 +0xec
testing.runTests(0x400000e090, {0x1a657b0, 0x1, 0x1}, {0x40005ffc88?, 0xd4400?, 0x1aa9920?})
	/usr/local/go/src/testing/testing.go:2159 +0x3b0
testing.(*M).Run(0x40004ac000)
	/usr/local/go/src/testing/testing.go:2027 +0x5a4
github.com/rancher/distros-test-framework/entrypoint/secretsencrypt.TestMain(0x40004ac000)
	/go/src/github.com/rancher/distros-test-framework/entrypoint/secretsencrypt/encryption_suite_test.go:31 +0xe4
main.main()
	_testmain.go:49 +0x170

goroutine 6 [select]:
go.opencensus.io/stats/view.(*worker).start(0x400048c500)
	/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x88
created by go.opencensus.io/stats/view.init.0 in goroutine 1
	/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x98

goroutine 36 [select, 38 minutes]:
github.com/onsi/ginkgo/v2/internal.(*Suite).runNode(_, {0x6, 0x4, {0xcac6ca, 0xe}, 0x40004904a0, {{0x14a7411, 0x5e}, 0x12, {0x0, ...}, ...}, ...}, ...)
	/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.16.0/internal/suite.go:911 +0xcdc
github.com/onsi/ginkgo/v2/internal.(*group).attemptSpec(0x40006a3148, 0x1, {{0x400065a708?, 0x40007983c0?, 0x1?}, 0x0?})
	/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.16.0/internal/group.go:199 +0x900
github.com/onsi/ginkgo/v2/internal.(*group).run(0x40006a3148, {0x40004b3740?, 0x0?, 0x0?})
	/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.16.0/internal/group.go:349 +0x840
github.com/onsi/ginkgo/v2/internal.(*Suite).runSpecs(0x400062c008, {0xcc2a23, 0x1d}, {0x1b12840, 0x0, 0x0}, {0x400004a004, 0x4b}, 0x0, {0x4000148800, ...})
	/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.16.0/internal/suite.go:489 +0x7e0
github.com/onsi/ginkgo/v2/internal.(*Suite).Run(_, {_, _}, {_, _, _}, {_, _}, _, {_, ...}, ...)
	/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.16.0/internal/suite.go:130 +0x2dc
github.com/onsi/ginkgo/v2.RunSpecs({0x1212920, 0x40004b61a0}, {0xcc2a23, 0x1d}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.16.0/core_dsl.go:300 +0x824
github.com/rancher/distros-test-framework/entrypoint/secretsencrypt.TestSecretsEncryptionSuite(0x40004b61a0)
	/go/src/github.com/rancher/distros-test-framework/entrypoint/secretsencrypt/encryption_suite_test.go:36 +0x50
testing.tRunner(0x40004b61a0, 0xd283c8)
	/usr/local/go/src/testing/testing.go:1689 +0xec
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1742 +0x318

goroutine 38 [syscall, 45 minutes]:
os/signal.signal_recv()
	/usr/local/go/src/runtime/sigqueue.go:152 +0x30
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x1c
created by os/signal.Notify.func1.1 in goroutine 36
	/usr/local/go/src/os/signal/signal.go:151 +0x28

goroutine 7 [select, 45 minutes]:
github.com/onsi/ginkgo/v2/internal/interrupt_handler.(*InterruptHandler).registerForInterrupts.func2(0x0?)
	/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.16.0/internal/interrupt_handler/interrupt_handler.go:131 +0x70
created by github.com/onsi/ginkgo/v2/internal/interrupt_handler.(*InterruptHandler).registerForInterrupts in goroutine 36
	/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.16.0/internal/interrupt_handler/interrupt_handler.go:128 +0x16c

goroutine 39 [select, 45 minutes]:
github.com/onsi/ginkgo/v2/internal.RegisterForProgressSignal.func1()
	/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.16.0/internal/progress_report.go:32 +0x8c
created by github.com/onsi/ginkgo/v2/internal.RegisterForProgressSignal in goroutine 36
	/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.16.0/internal/progress_report.go:30 +0xd8

goroutine 50 [select]:
github.com/onsi/gomega/internal.(*AsyncAssertion).match(0x40004c8cb0, {0x121c970, 0x400047fc20}, 0x1, {0x400047fc40, 0x1, 0x1})
	/go/pkg/mod/github.com/onsi/gomega@v1.31.1/internal/async_assertion.go:538 +0x5d0
github.com/onsi/gomega/internal.(*AsyncAssertion).Should(0x40004c8cb0, {0x121c970, 0x400047fc20}, {0x400047fc40, 0x1, 0x1})
	/go/pkg/mod/github.com/onsi/gomega@v1.31.1/internal/async_assertion.go:145 +0x7c
github.com/rancher/distros-test-framework/pkg/testcase.TestNodeStatus(0xd28588, 0x0)
	/go/src/github.com/rancher/distros-test-framework/pkg/testcase/node.go:40 +0x200
github.com/rancher/distros-test-framework/entrypoint/secretsencrypt.init.func3.2()
	/go/src/github.com/rancher/distros-test-framework/entrypoint/secretsencrypt/encryption_test.go:19 +0x28
github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func3({0x0?, 0x400049e4e0?})
	/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.16.0/internal/node.go:472 +0x24
github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()
	/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.16.0/internal/suite.go:889 +0x88
created by github.com/onsi/ginkgo/v2/internal.(*Suite).runNode in goroutine 36
	/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.16.0/internal/suite.go:876 +0xaf8
FAIL	github.com/rancher/distros-test-framework/entrypoint/secretsencrypt	2701.319s
FAIL
```

**Comment by aganesh-suse** [comment]
Settings: 
rke2_version="v1.27.12+rke2r1"
rke2_channel="latest"
server_flags   = ""
worker_flags   = ""

## Custom Vars
node_os            = "ubuntu"
aws_ami            = "<ubuntu_ami>"
aws_user           = "ubuntu"
# This is also known as an "all-roles" node
no_of_server_nodes = 0
no_of_worker_nodes = 1
split_roles        = true
etcd_only_nodes    = 1
etcd_cp_nodes      = 0
etcd_worker_nodes  = 0
cp_only_nodes      = 2
cp_worker_nodes    = 0
# Numbers 1-6 correspond to: all-roles (1), etcd-only (2), etcd-cp (3), etcd-worker (4), cp-only (5), cp-worker (6).
role_order         = "2,5"

**Comment by aganesh-suse** [comment]
We should definitely update the install scripts to add the node-external-ip in case of empty server flags - since it was missing in the config.yaml of the server. and kubectl get nodes -o wide was showing empty external IPs.
